### PR TITLE
Added shadow and support to Raymarched PBR

### PR DESCRIPTION
**Pull request by shadielhajj**
When using PBR with raymarching, soft shadows and ambient occlusion can be turned on with
- `#define RAYMARCH_SHADOWS`
- `#define RAYMARCH_AO`

Default raymarching material
Screenshot 2024-07-23 224507

Raymarched PBR
Screenshot 2024-07-23 230017

Raymarched PBR with soft shadows
Screenshot 2024-07-23 230027

Raymarched PBR with soft shadows and AO
Screenshot 2024-07-23 230040

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
Nice! Question, have this been tested with geometry?

**Comment by shadielhajj** [comment]
@patriciogonzalezvivo This works only with raymarching. But since it needs to be enabled explicitly (when the aforementioned #defines), current behaviour with meshes is unaffected.

**Comment by patriciogonzalezvivo** [comment]
Sweet. than you!

**Comment by patriciogonzalezvivo** [comment]
Getting this error when running https://github.com/patriciogonzalezvivo/lygia_examples/blob/main/lighting_pbrSsS.frag

image

Any ideas ?

**Comment by patriciogonzalezvivo** [comment]
mmm... seems is affecting code using `pbr()`

image

Happening in https://github.com/patriciogonzalezvivo/lygia_examples/blob/main/lighting_pbr.frag

**Comment by patriciogonzalezvivo** [comment]
Found the issue. Is the call for `#include "../raymarch/softShadow.glsl"` and #include "raymarch/ao.glsl". In point/directional lights and pbr function

**Comment by shadielhajj** [comment]
@patriciogonzalezvivo ooops. Let me see what's happening.

**Comment by patriciogonzalezvivo** [comment]
All good : ) I started the raymarching pipeline in a very messy way

**Pull request merged**
