### PR TITLE
Band-limited aafract (GLSL and HLSL)

### PR DESCRIPTION
**Pull request by shadielhajj**
Replaced the existing aafract with Frabrice Neyret's band-limited implementation, which deals much better with aliasing at high frequencies. This is a straightforward implementation and port of this algorithm: https://www.shadertoy.com/view/3tSGWy

Previous implementation
Screenshot 2024-07-07 223623

Proposed implementation
Screenshot 2024-07-07 223648

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
wow that's a huge difference! 
I checked the ShaderToy example and didn't find an explicit license, so it defaults to the [Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License](http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US)

Let's ping @FabriceNeyret and see if he is willing to grant MIT to it.

**Comment by FabriceNeyret** [comment]
On 08/07/2024 17:44, Patricio Gonzalez
      Vivo wrote:
    
    
      
      wow that's a huge difference!
        I checked the ShaderToy example and didn't find an explicit
        license, so it defaults to the Creative Commons
          Attribution-NonCommercial-ShareAlike 3.0 Unported License
      Let's ping @FabriceNeyret
        and see if he is willing to grant MIT to it.
      Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/patriciogonzalezvivo/lygia/pull/158#issuecomment-2214481617",
"url": "https://github.com/patriciogonzalezvivo/lygia/pull/158#issuecomment-2214481617",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    Uh, I miss like 100% of the context here  ( plus I have
      jelly-fish like memory if we already interacted. Still, I find no
      track in my mailboxes ).
      Who are you, what is different to what, which shadertoy, requested
      to do what, and which project does this
      ***@***.***
      refer to ? 
      :-)
    
    -- 
      
      Fabrice NEYRET

        --------------------------------------------
 equipe MAVERICK, laboratoire LJK/IMAG (CNRS,INPG,INRIA,UJF,UPMF)
         http://www-evasion.imag.fr/Membres/Fabrice.Neyret/
        --------------------------------------------

**Comment by FabriceNeyret** [comment]
Closing the thread had the advantage to send me a notification email that this time included a link to this page and this project, so I can now have a glimpse of the context and the project :-)
→ no problem to use the formula, go ahead, this are just base maths !  aliasing is a war against humanity that need worldwide cooperation :-D

**Comment by shadielhajj** [comment]
Thanks,  @FabriceNeyret! Much appreciated.

**Pull request closed without merging**
